import type { MarketingLocale } from "@/lib/marketing-locale";

import type { AuthMessages } from "./types";

const authMessagesEs: AuthMessages = {
  metaTitle: "Iniciar sesión",
  metaDescription: "Accede al panel de distribuidor Zumo.",
  subtitle: "Inicia sesión o crea una cuenta para tu espacio de trabajo.",
  langSwitcherAria: "Idioma",
  langEs: "ES",
  langEn: "EN",
  tabSignIn: "Iniciar sesión",
  tabSignUp: "Registrarse",
  signInTitle: "Bienvenido de nuevo",
  signInDescription: "Entra con tu correo y contraseña.",
  emailLabel: "Correo electrónico",
  emailPlaceholder: "tu@gmail.com",
  emailHint: "Puedes usar Gmail, Outlook u otro proveedor.",
  passwordLabel: "Contraseña",
  forgotPassword: "¿Olvidaste tu contraseña?",
  submitSignIn: "Iniciar sesión",
  signUpTitle: "Crea tu espacio",
  signUpDescription: "Indica los datos de tu negocio. Usa un correo que puedas verificar.",
  fullNameLabel: "Tu nombre completo",
  fullNamePlaceholder: "Ricardo Murillo",
  companyLabel: "Nombre del negocio",
  companyPlaceholder: "Distribuidora Central S.A.",
  phoneLabel: "Teléfono personal",
  phoneHint:
    "No escribas el código del país: lo aplicamos según el país que elijas.",
  phoneInvalid: "Introduce un número válido para el país seleccionado.",
  submitSignUp: "Crear cuenta",
  confirmTitle: "Verifica tu correo",
  confirmDescription: "Revisa tu bandeja. Te enviamos un código de verificación.",
  confirmCodeLabel: "Código de confirmación",
  confirmCodePlaceholder: "123456",
  submitConfirm: "Confirmar cuenta",
  backToSignIn: "Volver al inicio de sesión",
  backToLanding: "Volver al inicio",
  showPassword: "Mostrar contraseña",
  hidePassword: "Ocultar contraseña",
  toastPreview: "",
};

const authMessagesEn: AuthMessages = {
  metaTitle: "Sign in",
  metaDescription: "Access your Zumo distributor workspace.",
  subtitle: "Sign in or create an account for the distributor workspace.",
  langSwitcherAria: "Language",
  langEs: "ES",
  langEn: "EN",
  tabSignIn: "Sign in",
  tabSignUp: "Sign up",
  signInTitle: "Welcome back",
  signInDescription: "Sign in with your email and password.",
  emailLabel: "Email",
  emailPlaceholder: "you@gmail.com",
  emailHint: "Gmail, Outlook, or any email provider works.",
  passwordLabel: "Password",
  forgotPassword: "Forgot password?",
  submitSignIn: "Sign in",
  signUpTitle: "Create your workspace",
  signUpDescription: "Tell us about your business. Use an email you can verify.",
  fullNameLabel: "Your full name",
  fullNamePlaceholder: "Ricardo Murillo",
  companyLabel: "Company name",
  companyPlaceholder: "Central Foods LLC",
  phoneLabel: "Personal phone number",
  phoneHint: "Do not type the country code — we add it from your country selection.",
  phoneInvalid: "Enter a valid phone number for the selected country.",
  submitSignUp: "Create account",
  confirmTitle: "Verify your email",
  confirmDescription: "Check your inbox. We sent a verification code.",
  confirmCodeLabel: "Confirmation code",
  confirmCodePlaceholder: "123456",
  submitConfirm: "Confirm account",
  backToSignIn: "Back to sign in",
  backToLanding: "Back to home",
  showPassword: "Show password",
  hidePassword: "Hide password",
  toastPreview: "",
};

const catalog: Record<MarketingLocale, AuthMessages> = {
  es: authMessagesEs,
  en: authMessagesEn,
};

export function getAuthMessages(locale: MarketingLocale): AuthMessages {
  return catalog[locale];
}
