export type AuthMessages = {
  metaTitle: string;
  metaDescription: string;
  subtitle: string;
  langSwitcherAria: string;
  langEs: string;
  langEn: string;
  tabSignIn: string;
  tabSignUp: string;
  signInTitle: string;
  signInDescription: string;
  emailLabel: string;
  emailPlaceholder: string;
  emailHint: string;
  passwordLabel: string;
  forgotPassword: string;
  submitSignIn: string;
  signUpTitle: string;
  signUpDescription: string;
  fullNameLabel: string;
  fullNamePlaceholder: string;
  companyLabel: string;
  companyPlaceholder: string;
  submitSignUp: string;
  confirmTitle: string;
  confirmDescription: string;
  confirmCodeLabel: string;
  confirmCodePlaceholder: string;
  submitConfirm: string;
  backToSignIn: string;
  backToLanding: string;
  showPassword: string;
  hidePassword: string;
  /** @deprecated kept for TS compat with existing callers */
  toastPreview: string;
};
